### ISSUE TITLE
how can I implement my own json data

### ISSUE THREAD

**Issue by akerimyildiz94** [omnisci/mapd-charting#133]
Hello,
Thank you for creating this platform.

I want to implement my own json data which I get from a service. So I see that mapd-crossfilter does not support that as original crossfilter. So how can I make it work with my own json data?

**Comment by jrajav** [comment]
Thanks for your interest @akerimyildiz94 ! mapd-charting is intended for usage with OmniSci, via mapd-crossfilter and mapd-connector, so we don't directly support this use case.
