### ISSUE TITLE
Fix Webpack Build

### ISSUE THREAD

**Issue by clhenrick** [omnisci/mapd-charting#215]
Currently the webpack build script compiles the code in a way where nothing is actually exposed. This is because `src/index.js` only `export`s individual modules and does not `export` them under a single `dc` namespace. There's also some tricky stuff going on like the `require()`'ing of our forked version MapboxGL and D3JS v3.x.  

#212 starts to address this but still needs some work.

**Comment by jrajav** [comment]
Tracking in Jira now.
