### ISSUE TITLE
Golden Ratio prime number in Knuth Multiplicative Hash is wrong! (and not prime!)

### ISSUE THREAD

**Issue by simoneves** [omnisci/mapd-charting#239]
The prime number that appears to be defined as GOLDEN_RATIO in maps-connector/dist/mapdc.js, that makes its way into the SQL of a point render query for density reduction is wrong

It should be 26544**3**5761 not 265445761.

The latter is not even prime. It's a multiple of 7.

**Comment by simoneves** [comment]
OK, so that's a baked distribution bundle, not the original. I can't find the original. But it's still wrong.

**Comment by simoneves** [comment]
Assigning he who made the original typo... ;)

**Comment by tmostak** [comment]
It was in crossfilter, PR can be found here: https://github.com/mapd/mapd-crossfilter/pull/60.  Assigning @clhenrick to review. :)

**Comment by tmostak** [comment]
Also here: https://github.com/mapd/metis/pull/33
