### ISSUE TITLE
does mapd-charting work only with mapbox?

### ISSUE THREAD

**Issue by maulikit** [omnisci/mapd-charting#240]
in the example2.html file, var pointMapChart is initialized using dc.mapboxtoken, also we need to include mapboxgl as a dependency. I want to confirm if we can make use of any other map providers as our base layer and use mapd-charting backend rendered images on top of the basemap?

**Comment by vastcharade** [comment]
unfortunately mapd-charting is tied to mapbox. We have plans for a future revision of the charting layer to be basemap agnostic, but don't expect that anytime soon.

If you're only interested in pointmap, and are ambitious enough, then you might be able to replace the mapbox dependency with whatever basemap you wanted to play with. The biggest changes needed would be in https://github.com/mapd/mapd-charting/blob/master/src/mixins/map-mixin.js
That's where most of the mapbox-dependent stuff is happening.

**Comment by maulikit** [comment]
Thanks! will check the file. i would be most interested in pointmaps and heatmaps.
