### ISSUE TITLE
how to add 'reset'  method to my chart as dc.js？

### ISSUE THREAD

**Issue by Keekuun** [omnisci/mapd-charting#308]

**Comment by jrajav** [comment]
Hi @Keekuun - can you give an example of the 'reset' method's usage and what you'd expect it to be doing?

**Comment by Keekuun** [comment]
I have a project with dc.js. But I don't know how to add "reset" when I use mapd-charting.
When cross-filtered data, it helps to reset the chart.
The 'reset' in Dc.js:
` <a class="reset" href="javascript:moveChart.filterAll();volumeChart.filterAll();dc.redrawAll();"
           style="display: none;">reset</a>`

**Comment by Keekuun** [comment]
> Hi @Keekuun - can you give an example of the 'reset' method's usage and what you'd expect it to be doing?

Thanks for your replay.
