### ISSUE TITLE
how to install mapd-charting on ubuntu 16 or other linux-like operating system?

### ISSUE THREAD

**Issue by dengjinli** [omnisci/mapd-charting#88]
## :beetle: If bug
  - [ ] Operating System and version:
  - [ ] Browser and version:
  - [ ] Steps to reproduce (including dashboard link):
  - [ ] Description of issue:

## :new: If feature request  
  - [ ] User story:
  - [ ] Specific requirements/functionality:
  - [ ] Mocks (if applicable):

**Comment by codetricity** [comment]
Use node 5.x, like node 5.12. Use nvm or n.  see my experience on Ubuntu 17.10, which should be the same. If you have problems, you can write a question on that blog and I'll try and help you.

**Comment by jrajav** [comment]
We currently support Node v8 and above for mapd-charting. If you have this installed and still run into problems, please open a follow-up issue. Thanks!
